apiVersion:  apps/v1
kind:  Deployment
metadata:
  name:  postgres
  labels:
    app: postgres_deployment
  namespace: k8s-demo
spec:
  replicas:  1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "userdb"
        - name: POSTGRES_USER
          value: "microadmin"
        - name: POSTGRES_PASSWORD
          value: "microadmin"
        ports:
        - containerPort: 5432
